// marketplaceSellerConstants.js
export const CREATE_MARKETPLACE_SELLER_REQUEST =
  "CREATE_MARKETPLACE_SELLER_REQUEST";
export const CREATE_MARKETPLACE_SELLER_SUCCESS =
  "CREATE_MARKETPLACE_SELLER_SUCCESS";
export const CREATE_MARKETPLACE_SELLER_FAIL = "CREATE_MARKETPLACE_SELLER_FAIL";

export const GET_SELLER_ACCOUNT_REQUEST = "GET_SELLER_ACCOUNT_REQUEST";
export const GET_SELLER_ACCOUNT_SUCCESS = "GET_SELLER_ACCOUNT_SUCCESS";
export const GET_SELLER_ACCOUNT_FAIL = "GET_SELLER_ACCOUNT_FAIL";

export const UPDATE_SELLER_ACCOUNT_REQUEST = "UPDATE_SELLER_ACCOUNT_REQUEST";
export const UPDATE_SELLER_ACCOUNT_SUCCESS = "UPDATE_SELLER_ACCOUNT_SUCCESS";
export const UPDATE_SELLER_ACCOUNT_FAIL = "UPDATE_SELLER_ACCOUNT_FAIL";

export const MARKETPLACE_SELLER_PHOTO_REQUEST =
  "MARKETPLACE_SELLER_PHOTO_REQUEST";
export const MARKETPLACE_SELLER_PHOTO_SUCCESS =
  "MARKETPLACE_SELLER_PHOTO_SUCCESS";
export const MARKETPLACE_SELLER_PHOTO_FAIL = "MARKETPLACE_SELLER_PHOTO_FAIL";

export const GET_SELLER_PHOTO_REQUEST = "GET_SELLER_PHOTO_REQUEST";
export const GET_SELLER_PHOTO_SUCCESS = "GET_SELLER_PHOTO_SUCCESS";
export const GET_SELLER_PHOTO_FAIL = "GET_SELLER_PHOTO_FAIL";
export const UPDATE_SELLER_PHOTO_REQUEST = "UPDATE_SELLER_PHOTO_REQUEST";
export const UPDATE_SELLER_PHOTO_SUCCESS = "UPDATE_SELLER_PHOTO_SUCCESS";
export const UPDATE_SELLER_PHOTO_FAIL = "UPDATE_SELLER_PHOTO_FAIL";

export const POST_FREE_AD_REQUEST = "POST_FREE_AD_REQUEST";
export const POST_FREE_AD_SUCCESS = "POST_FREE_AD_SUCCESS";
export const POST_FREE_AD_FAIL = "POST_FREE_AD_FAIL";

export const POST_PAID_AD_REQUEST = "POST_PAID_AD_REQUEST";
export const POST_PAID_AD_SUCCESS = "POST_PAID_AD_SUCCESS";
export const POST_PAID_AD_FAIL = "POST_PAID_AD_FAIL";

export const GET_FREE_AD_REQUEST = "GET_FREE_AD_REQUEST";
export const GET_FREE_AD_SUCCESS = "GET_FREE_AD_SUCCESS";
export const GET_FREE_AD_FAIL = "GET_FREE_AD_FAIL";

export const GET_FREE_AD_DETAIL_REQUEST = "GET_FREE_AD_DETAIL_REQUEST";
export const GET_FREE_AD_DETAIL_SUCCESS = "GET_FREE_AD_DETAIL_SUCCESS";
export const GET_FREE_AD_DETAIL_FAIL = "GET_FREE_AD_DETAIL_FAIL";

export const UPDATE_FREE_AD_REQUEST = "UPDATE_FREE_AD_REQUEST";
export const UPDATE_FREE_AD_SUCCESS = "UPDATE_FREE_AD_SUCCESS";
export const UPDATE_FREE_AD_FAIL = "UPDATE_FREE_AD_FAIL";

export const DELETE_FREE_AD_REQUEST = "DELETE_FREE_AD_REQUEST";
export const DELETE_FREE_AD_SUCCESS = "DELETE_FREE_AD_SUCCESS";
export const DELETE_FREE_AD_FAIL = "DELETE_FREE_AD_FAIL";

export const GET_ALL_FREE_AD_REQUEST = "GET_ALL_FREE_AD_REQUEST";
export const GET_ALL_FREE_AD_SUCCESS = "GET_ALL_FREE_AD_SUCCESS";
export const GET_ALL_FREE_AD_FAIL = "GET_ALL_FREE_AD_FAIL";

export const GET_PAID_AD_REQUEST = "GET_PAID_AD_REQUEST";
export const GET_PAID_AD_SUCCESS = "GET_PAID_AD_SUCCESS";
export const GET_PAID_AD_FAIL = "GET_PAID_AD_FAIL";

export const GET_PAID_AD_DETAIL_REQUEST = "GET_PAID_AD_DETAIL_REQUEST";
export const GET_PAID_AD_DETAIL_SUCCESS = "GET_PAID_AD_DETAIL_SUCCESS";
export const GET_PAID_AD_DETAIL_FAIL = "GET_PAID_AD_DETAIL_FAIL";

export const UPDATE_PAID_AD_REQUEST = "UPDATE_PAID_AD_REQUEST";
export const UPDATE_PAID_AD_SUCCESS = "UPDATE_PAID_AD_SUCCESS";
export const UPDATE_PAID_AD_FAIL = "UPDATE_PAID_AD_FAIL";

export const DELETE_PAID_AD_REQUEST = "DELETE_PAID_AD_REQUEST";
export const DELETE_PAID_AD_SUCCESS = "DELETE_PAID_AD_SUCCESS";
export const DELETE_PAID_AD_FAIL = "DELETE_PAID_AD_FAIL";

export const GET_ALL_PAID_AD_REQUEST = "GET_ALL_PAID_AD_REQUEST";
export const GET_ALL_PAID_AD_SUCCESS = "GET_ALL_PAID_AD_SUCCESS";
export const GET_ALL_PAID_AD_FAIL = "GET_ALL_PAID_AD_FAIL";

export const GET_SELLER_API_KEY_REQUEST = "GET_SELLER_API_KEY_REQUEST";
export const GET_SELLER_API_KEY_SUCCESS = "GET_SELLER_API_KEY_SUCCESS";
export const GET_SELLER_API_KEY_FAIL = "GET_SELLER_API_KEY_FAIL";

export const UPDATE_SELLER_API_KEY_REQUEST = "UPDATE_SELLER_API_KEY_REQUEST";
export const UPDATE_SELLER_API_KEY_SUCCESS = "UPDATE_SELLER_API_KEY_SUCCESS";
export const UPDATE_SELLER_API_KEY_FAIL = "UPDATE_SELLER_API_KEY_FAIL";

export const CREATE_PAID_AD_MESSAGE_REQUEST = "CREATE_PAID_AD_MESSAGE_REQUEST";
export const CREATE_PAID_AD_MESSAGE_SUCCESS = "CREATE_PAID_AD_MESSAGE_SUCCESS";
export const CREATE_PAID_AD_MESSAGE_FAIL = "CREATE_PAID_AD_MESSAGE_FAIL";

export const LIST_PAID_AD_MESSAGE_REQUEST = "LIST_PAID_AD_MESSAGE_REQUEST";
export const LIST_PAID_AD_MESSAGE_SUCCESS = "LIST_PAID_AD_MESSAGE_SUCCESS";
export const LIST_PAID_AD_MESSAGE_FAIL = "LIST_PAID_AD_MESSAGE_FAIL";

export const CREATE_FREE_AD_MESSAGE_REQUEST = "CREATE_FREE_AD_MESSAGE_REQUEST";
export const CREATE_FREE_AD_MESSAGE_SUCCESS = "CREATE_FREE_AD_MESSAGE_SUCCESS";
export const CREATE_FREE_AD_MESSAGE_FAIL = "CREATE_FREE_AD_MESSAGE_FAIL";

export const LIST_FREE_AD_MESSAGE_REQUEST = "LIST_FREE_AD_MESSAGE_REQUEST";
export const LIST_FREE_AD_MESSAGE_SUCCESS = "LIST_FREE_AD_MESSAGE_SUCCESS";
export const LIST_FREE_AD_MESSAGE_FAIL = "LIST_FREE_AD_MESSAGE_FAIL";

export const EDIT_PAID_AD_REQUEST = "EDIT_PAID_AD_REQUEST";
export const EDIT_PAID_AD_SUCCESS = "EDIT_PAID_AD_SUCCESS";
export const EDIT_PAID_AD_FAIL = "EDIT_PAID_AD_FAIL";

export const DEACTIVATE_PAID_AD_REQUEST = "DEACTIVATE_PAID_AD_REQUEST";
export const DEACTIVATE_PAID_AD_SUCCESS = "DEACTIVATE_PAID_AD_SUCCESS";
export const DEACTIVATE_PAID_AD_FAIL = "DEACTIVATE_PAID_AD_FAIL";

export const REACTIVATE_PAID_AD_REQUEST = "REACTIVATE_PAID_AD_REQUEST";
export const REACTIVATE_PAID_AD_SUCCESS = "REACTIVATE_PAID_AD_SUCCESS";
export const REACTIVATE_PAID_AD_FAIL = "REACTIVATE_PAID_AD_FAIL";

export const DEACTIVATE_FREE_AD_REQUEST = "DEACTIVATE_FREE_AD_REQUEST";
export const DEACTIVATE_FREE_AD_SUCCESS = "DEACTIVATE_FREE_AD_SUCCESS";
export const DEACTIVATE_FREE_AD_FAIL = "DEACTIVATE_FREE_AD_FAIL";

export const REACTIVATE_FREE_AD_REQUEST = "REACTIVATE_FREE_AD_REQUEST";
export const REACTIVATE_FREE_AD_SUCCESS = "REACTIVATE_FREE_AD_SUCCESS";
export const REACTIVATE_FREE_AD_FAIL = "REACTIVATE_FREE_AD_FAIL";

export const EDIT_FREE_AD_REQUEST = "EDIT_FREE_AD_REQUEST";
export const EDIT_FREE_AD_SUCCESS = "EDIT_FREE_AD_SUCCESS";
export const EDIT_FREE_AD_FAIL = "EDIT_FREE_AD_FAIL";

export const GET_SELLER_ACTIVE_PAID_ADS_REQUEST = "GET_SELLER_ACTIVE_PAID_ADS_REQUEST";
export const GET_SELLER_ACTIVE_PAID_ADS_SUCCESS = "GET_SELLER_ACTIVE_PAID_ADS_SUCCESS";
export const GET_SELLER_ACTIVE_PAID_ADS_FAIL = "GET_SELLER_ACTIVE_PAID_ADS_FAIL";

export const GET_SELLER_ACTIVE_FREE_ADS_REQUEST = "GET_SELLER_ACTIVE_FREE_ADS_REQUEST";
export const GET_SELLER_ACTIVE_FREE_ADS_SUCCESS = "GET_SELLER_ACTIVE_FREE_ADS_SUCCESS";
export const GET_SELLER_ACTIVE_FREE_ADS_FAIL = "GET_SELLER_ACTIVE_FREE_ADS_FAIL";

export const GET_SELLER_USERNAME_SEARCH_REQUEST = "GET_SELLER_USERNAME_SEARCH_REQUEST";
export const GET_SELLER_USERNAME_SEARCH_SUCCESS = "GET_SELLER_USERNAME_SEARCH_SUCCESS";
export const GET_SELLER_USERNAME_SEARCH_FAIL = "GET_SELLER_USERNAME_SEARCH_FAIL";

export const GET_SELLER_DETAIL_REQUEST = "GET_SELLER_DETAIL_REQUEST";
export const GET_SELLER_DETAIL_SUCCESS = "GET_SELLER_DETAIL_SUCCESS";
export const GET_SELLER_DETAIL_FAIL = "GET_SELLER_DETAIL_FAIL";

export const SEARCH_ADS_REQUEST = "SEARCH_ADS_REQUEST";
export const SEARCH_ADS_SUCCESS = "SEARCH_ADS_SUCCESS";
export const SEARCH_ADS_FAIL = "SEARCH_ADS_FAIL";

export const GET_SELLER_SHOPFRONT_LINK_REQUEST = "GET_SELLER_SHOPFRONT_LINK_REQUEST";
export const GET_SELLER_SHOPFRONT_LINK_SUCCESS = "GET_SELLER_SHOPFRONT_LINK_SUCCESS";
export const GET_SELLER_SHOPFRONT_LINK_FAIL = "GET_SELLER_SHOPFRONT_LINK_FAIL";
