// marketplaceSellerConstants.js
export const CREATE_MARKETPLACE_SELLER_REQUEST =
  "CREATE_MARKETPLACE_SELLER_REQUEST";
export const CREATE_MARKETPLACE_SELLER_SUCCESS =
  "CREATE_MARKETPLACE_SELLER_SUCCESS";
export const CREATE_MARKETPLACE_SELLER_FAIL = "CREATE_MARKETPLACE_SELLER_FAIL";

export const GET_SELLER_ACCOUNT_REQUEST = "GET_SELLER_ACCOUNT_REQUEST";
export const GET_SELLER_ACCOUNT_SUCCESS = "GET_SELLER_ACCOUNT_SUCCESS";
export const GET_SELLER_ACCOUNT_FAIL = "GET_SELLER_ACCOUNT_FAIL";

export const UPDATE_SELLER_ACCOUNT_REQUEST = "UPDATE_SELLER_ACCOUNT_REQUEST"; 
export const UPDATE_SELLER_ACCOUNT_SUCCESS = "UPDATE_SELLER_ACCOUNT_SUCCESS";
export const UPDATE_SELLER_ACCOUNT_FAIL = "UPDATE_SELLER_ACCOUNT_FAIL";

export const MARKETPLACE_SELLER_PHOTO_REQUEST =
  "MARKETPLACE_SELLER_PHOTO_REQUEST";
export const MARKETPLACE_SELLER_PHOTO_SUCCESS =
  "MARKETPLACE_SELLER_PHOTO_SUCCESS";
export const MARKETPLACE_SELLER_PHOTO_FAIL = "MARKETPLACE_SELLER_PHOTO_FAIL";

export const GET_SELLER_PHOTO_REQUEST = "GET_SELLER_PHOTO_REQUEST";
export const GET_SELLER_PHOTO_SUCCESS = "GET_SELLER_PHOTO_SUCCESS";
export const GET_SELLER_PHOTO_FAIL = "GET_SELLER_PHOTO_FAIL";
export const UPDATE_SELLER_PHOTO_REQUEST = "UPDATE_SELLER_PHOTO_REQUEST";
export const UPDATE_SELLER_PHOTO_SUCCESS = "UPDATE_SELLER_PHOTO_SUCCESS";
export const UPDATE_SELLER_PHOTO_FAIL = "UPDATE_SELLER_PHOTO_FAIL";

export const POST_FREE_AD_REQUEST = "POST_FREE_AD_REQUEST";
export const POST_FREE_AD_SUCCESS = "POST_FREE_AD_SUCCESS";
export const POST_FREE_AD_FAIL = "POST_FREE_AD_FAIL";

export const POST_PAID_AD_REQUEST = "POST_PAID_AD_REQUEST";
export const POST_PAID_AD_SUCCESS = "POST_PAID_AD_SUCCESS";
export const POST_PAID_AD_FAIL = "POST_PAID_AD_FAIL";

export const GET_FREE_AD_REQUEST = "GET_FREE_AD_REQUEST";
export const GET_FREE_AD_SUCCESS = "GET_FREE_AD_SUCCESS";
export const GET_FREE_AD_FAIL = "GET_FREE_AD_FAIL";

export const GET_FREE_AD_DETAIL_REQUEST = "GET_FREE_AD_DETAIL_REQUEST";
export const GET_FREE_AD_DETAIL_SUCCESS = "GET_FREE_AD_DETAIL_SUCCESS";
export const GET_FREE_AD_DETAIL_FAIL = "GET_FREE_AD_DETAIL_FAIL";

export const UPDATE_FREE_AD_REQUEST = "UPDATE_FREE_AD_REQUEST";
export const UPDATE_FREE_AD_SUCCESS = "UPDATE_FREE_AD_SUCCESS";
export const UPDATE_FREE_AD_FAIL = "UPDATE_FREE_AD_FAIL";

export const DELETE_FREE_AD_REQUEST = "DELETE_FREE_AD_REQUEST";
export const DELETE_FREE_AD_SUCCESS = "DELETE_FREE_AD_SUCCESS";
export const DELETE_FREE_AD_FAIL = "DELETE_FREE_AD_FAIL";

export const GET_ALL_FREE_AD_REQUEST = "GET_ALL_FREE_AD_REQUEST";
export const GET_ALL_FREE_AD_SUCCESS = "GET_ALL_FREE_AD_SUCCESS";
export const GET_ALL_FREE_AD_FAIL = "GET_ALL_FREE_AD_FAIL";

export const GET_PAID_AD_REQUEST = "GET_PAID_AD_REQUEST";
export const GET_PAID_AD_SUCCESS = "GET_PAID_AD_SUCCESS";
export const GET_PAID_AD_FAIL = "GET_PAID_AD_FAIL";

export const GET_PAID_AD_DETAIL_REQUEST = "GET_PAID_AD_DETAIL_REQUEST";
export const GET_PAID_AD_DETAIL_SUCCESS = "GET_PAID_AD_DETAIL_SUCCESS";
export const GET_PAID_AD_DETAIL_FAIL = "GET_PAID_AD_DETAIL_FAIL";

export const UPDATE_PAID_AD_REQUEST = "UPDATE_PAID_AD_REQUEST";
export const UPDATE_PAID_AD_SUCCESS = "UPDATE_PAID_AD_SUCCESS";
export const UPDATE_PAID_AD_FAIL = "UPDATE_PAID_AD_FAIL";

export const DELETE_PAID_AD_REQUEST = "DELETE_PAID_AD_REQUEST";
export const DELETE_PAID_AD_SUCCESS = "DELETE_PAID_AD_SUCCESS";
export const DELETE_PAID_AD_FAIL = "DELETE_PAID_AD_FAIL";

export const GET_ALL_PAID_AD_REQUEST = "GET_ALL_PAID_AD_REQUEST";
export const GET_ALL_PAID_AD_SUCCESS = "GET_ALL_PAID_AD_SUCCESS";
export const GET_ALL_PAID_AD_FAIL = "GET_ALL_PAID_AD_FAIL";

export const GET_SELLER_API_KEY_REQUEST = "GET_SELLER_API_KEY_REQUEST";
export const GET_SELLER_API_KEY_SUCCESS = "GET_SELLER_API_KEY_SUCCESS";
export const GET_SELLER_API_KEY_FAIL = "GET_SELLER_API_KEY_FAIL";

export const UPDATE_SELLER_API_KEY_REQUEST = "UPDATE_SELLER_API_KEY_REQUEST";
export const UPDATE_SELLER_API_KEY_SUCCESS = "UPDATE_SELLER_API_KEY_SUCCESS";
export const UPDATE_SELLER_API_KEY_FAIL = "UPDATE_SELLER_API_KEY_FAIL";

export const CREATE_PAID_AD_MESSAGE_REQUEST = "CREATE_PAID_AD_MESSAGE_REQUEST";
export const CREATE_PAID_AD_MESSAGE_SUCCESS = "CREATE_PAID_AD_MESSAGE_SUCCESS";
export const CREATE_PAID_AD_MESSAGE_FAIL = "CREATE_PAID_AD_MESSAGE_FAIL";

export const LIST_PAID_AD_MESSAGE_REQUEST = "LIST_PAID_AD_MESSAGE_REQUEST";
export const LIST_PAID_AD_MESSAGE_SUCCESS = "LIST_PAID_AD_MESSAGE_SUCCESS";
export const LIST_PAID_AD_MESSAGE_FAIL = "LIST_PAID_AD_MESSAGE_FAIL";

export const CREATE_FREE_AD_MESSAGE_REQUEST = "CREATE_FREE_AD_MESSAGE_REQUEST";
export const CREATE_FREE_AD_MESSAGE_SUCCESS = "CREATE_FREE_AD_MESSAGE_SUCCESS";
export const CREATE_FREE_AD_MESSAGE_FAIL = "CREATE_FREE_AD_MESSAGE_FAIL";

export const LIST_FREE_AD_MESSAGE_REQUEST = "LIST_FREE_AD_MESSAGE_REQUEST";
export const LIST_FREE_AD_MESSAGE_SUCCESS = "LIST_FREE_AD_MESSAGE_SUCCESS";
export const LIST_FREE_AD_MESSAGE_FAIL = "LIST_FREE_AD_MESSAGE_FAIL";

export const EDIT_PAID_AD_REQUEST = "EDIT_PAID_AD_REQUEST";
export const EDIT_PAID_AD_SUCCESS = "EDIT_PAID_AD_SUCCESS";
export const EDIT_PAID_AD_FAIL = "EDIT_PAID_AD_FAIL";

export const DEACTIVATE_PAID_AD_REQUEST = "DEACTIVATE_PAID_AD_REQUEST";
export const DEACTIVATE_PAID_AD_SUCCESS = "DEACTIVATE_PAID_AD_SUCCESS";
export const DEACTIVATE_PAID_AD_FAIL = "DEACTIVATE_PAID_AD_FAIL";

export const REACTIVATE_PAID_AD_REQUEST = "REACTIVATE_PAID_AD_REQUEST";
export const REACTIVATE_PAID_AD_SUCCESS = "REACTIVATE_PAID_AD_SUCCESS";
export const REACTIVATE_PAID_AD_FAIL = "REACTIVATE_PAID_AD_FAIL";

export const DEACTIVATE_FREE_AD_REQUEST = "DEACTIVATE_FREE_AD_REQUEST";
export const DEACTIVATE_FREE_AD_SUCCESS = "DEACTIVATE_FREE_AD_SUCCESS";
export const DEACTIVATE_FREE_AD_FAIL = "DEACTIVATE_FREE_AD_FAIL";

export const REACTIVATE_FREE_AD_REQUEST = "REACTIVATE_FREE_AD_REQUEST";
export const REACTIVATE_FREE_AD_SUCCESS = "REACTIVATE_FREE_AD_SUCCESS";
export const REACTIVATE_FREE_AD_FAIL = "REACTIVATE_FREE_AD_FAIL";

export const EDIT_FREE_AD_REQUEST = "EDIT_FREE_AD_REQUEST";
export const EDIT_FREE_AD_SUCCESS = "EDIT_FREE_AD_SUCCESS";
export const EDIT_FREE_AD_FAIL = "EDIT_FREE_AD_FAIL";

export const GET_SELLER_ACTIVE_PAID_ADS_REQUEST = "GET_SELLER_ACTIVE_PAID_ADS_REQUEST";
export const GET_SELLER_ACTIVE_PAID_ADS_SUCCESS = "GET_SELLER_ACTIVE_PAID_ADS_SUCCESS";
export const GET_SELLER_ACTIVE_PAID_ADS_FAIL = "GET_SELLER_ACTIVE_PAID_ADS_FAIL";

export const GET_SELLER_ACTIVE_FREE_ADS_REQUEST = "GET_SELLER_ACTIVE_FREE_ADS_REQUEST";
export const GET_SELLER_ACTIVE_FREE_ADS_SUCCESS = "GET_SELLER_ACTIVE_FREE_ADS_SUCCESS";
export const GET_SELLER_ACTIVE_FREE_ADS_FAIL = "GET_SELLER_ACTIVE_FREE_ADS_FAIL";

export const GET_SELLER_USERNAME_SEARCH_REQUEST = "GET_SELLER_USERNAME_SEARCH_REQUEST";
export const GET_SELLER_USERNAME_SEARCH_SUCCESS = "GET_SELLER_USERNAME_SEARCH_SUCCESS";
export const GET_SELLER_USERNAME_SEARCH_FAIL = "GET_SELLER_USERNAME_SEARCH_FAIL";

export const GET_SELLER_DETAIL_REQUEST = "GET_SELLER_DETAIL_REQUEST";
export const GET_SELLER_DETAIL_SUCCESS = "GET_SELLER_DETAIL_SUCCESS";
export const GET_SELLER_DETAIL_FAIL = "GET_SELLER_DETAIL_FAIL";

export const SEARCH_ADS_REQUEST = "SEARCH_ADS_REQUEST";
export const SEARCH_ADS_SUCCESS = "SEARCH_ADS_SUCCESS";
export const SEARCH_ADS_FAIL = "SEARCH_ADS_FAIL";

export const GET_SELLER_SHOPFRONT_LINK_REQUEST = "GET_SELLER_SHOPFRONT_LINK_REQUEST";
export const GET_SELLER_SHOPFRONT_LINK_SUCCESS = "GET_SELLER_SHOPFRONT_LINK_SUCCESS";
export const GET_SELLER_SHOPFRONT_LINK_FAIL = "GET_SELLER_SHOPFRONT_LINK_FAIL"; 

export const REPORT_FREE_AD_REQUEST = "REPORT_FREE_AD_REQUEST";
export const REPORT_FREE_AD_SUCCESS = "REPORT_FREE_AD_SUCCESS";
export const REPORT_FREE_AD_FAIL = "REPORT_FREE_AD_FAIL";

export const REPORT_PAID_AD_REQUEST = "REPORT_PAID_AD_REQUEST";
export const REPORT_PAID_AD_SUCCESS = "REPORT_PAID_AD_SUCCESS";
export const REPORT_PAID_AD_FAIL = "REPORT_PAID_AD_FAIL";

export const SELLER_REPLY_FREE_AD_MESSAGE_REQUEST = "SELLER_REPLY_FREE_AD_MESSAGE_REQUEST";
export const SELLER_REPLY_FREE_AD_MESSAGE_SUCCESS = "SELLER_REPLY_FREE_AD_MESSAGE_SUCCESS";
export const SELLER_REPLY_FREE_AD_MESSAGE_FAIL = "SELLER_REPLY_FREE_AD_MESSAGE_FAIL";

export const SELLER_REPLY_PAID_AD_MESSAGE_REQUEST = "SELLER_REPLY_PAID_AD_MESSAGE_REQUEST";
export const SELLER_REPLY_PAID_AD_MESSAGE_SUCCESS = "SELLER_REPLY_PAID_AD_MESSAGE_SUCCESS";
export const SELLER_REPLY_PAID_AD_MESSAGE_FAIL = "SELLER_REPLY_PAID_AD_MESSAGE_FAIL";

export const LIST_SELLER_FREE_AD_MESSAGES_REQUEST = "LIST_SELLER_FREE_AD_MESSAGES_REQUEST";
export const LIST_SELLER_FREE_AD_MESSAGES_SUCCESS = "LIST_SELLER_FREE_AD_MESSAGES_SUCCESS";
export const LIST_SELLER_FREE_AD_MESSAGES_FAIL = "LIST_SELLER_FREE_AD_MESSAGES_FAIL";

export const LIST_SELLER_PAID_AD_MESSAGES_REQUEST = "LIST_SELLER_PAID_AD_MESSAGES_REQUEST";
export const LIST_SELLER_PAID_AD_MESSAGES_SUCCESS = "LIST_SELLER_PAID_AD_MESSAGES_SUCCESS";
export const LIST_SELLER_PAID_AD_MESSAGES_FAIL = "LIST_SELLER_PAID_AD_MESSAGES_FAIL";

export const GET_BUYER_FREE_AD_MESSAGES_REQUEST = "GET_BUYER_FREE_AD_MESSAGES_REQUEST";
export const GET_BUYER_FREE_AD_MESSAGES_SUCCESS = "GET_BUYER_FREE_AD_MESSAGES_SUCCESS";
export const GET_BUYER_FREE_AD_MESSAGES_FAIL = "GET_BUYER_FREE_AD_MESSAGES_FAIL";

export const GET_BUYER_PAID_AD_MESSAGES_REQUEST = "GET_BUYER_PAID_AD_MESSAGES_REQUEST";
export const GET_BUYER_PAID_AD_MESSAGES_SUCCESS = "GET_BUYER_PAID_AD_MESSAGES_SUCCESS";
export const GET_BUYER_PAID_AD_MESSAGES_FAIL = "GET_BUYER_PAID_AD_MESSAGES_FAIL";

export const TOGGLE_FREE_AD_SAVE_REQUEST = "TOGGLE_FREE_AD_SAVE_REQUEST";
export const TOGGLE_FREE_AD_SAVE_SUCCESS = "TOGGLE_FREE_AD_SAVE_SUCCESS";
export const TOGGLE_FREE_AD_SAVE_FAIL = "TOGGLE_FREE_AD_SAVE_FAIL";

export const TOGGLE_PAID_AD_SAVE_REQUEST = "TOGGLE_PAID_AD_SAVE_REQUEST";
export const TOGGLE_PAID_AD_SAVE_SUCCESS = "TOGGLE_PAID_AD_SAVE_SUCCESS";
export const TOGGLE_PAID_AD_SAVE_FAIL = "TOGGLE_PAID_AD_SAVE_FAIL";

export const TRACK_FREE_AD_VIEW_REQUEST = "TRACK_FREE_AD_VIEW_REQUEST";
export const TRACK_FREE_AD_VIEW_SUCCESS = "TRACK_FREE_AD_VIEW_SUCCESS";
export const TRACK_FREE_AD_VIEW_FAIL = "TRACK_FREE_AD_VIEW_FAIL";

export const TRACK_PAID_AD_VIEW_REQUEST = "TRACK_PAID_AD_VIEW_REQUEST";
export const TRACK_PAID_AD_VIEW_SUCCESS = "TRACK_PAID_AD_VIEW_SUCCESS";
export const TRACK_PAID_AD_VIEW_FAIL = "TRACK_PAID_AD_VIEW_FAIL";

export const GET_USER_VIEWED_FREE_ADS_REQUEST = "GET_USER_VIEWED_FREE_ADS_REQUEST";
export const GET_USER_VIEWED_FREE_ADS_SUCCESS = "GET_USER_VIEWED_FREE_ADS_SUCCESS";
export const GET_USER_VIEWED_FREE_ADS_FAIL = "GET_USER_VIEWED_FREE_ADS_FAIL";

export const GET_USER_VIEWED_PAID_ADS_REQUEST = "GET_USER_VIEWED_PAID_ADS_REQUEST";
export const GET_USER_VIEWED_PAID_ADS_SUCCESS = "GET_USER_VIEWED_PAID_ADS_SUCCESS";
export const GET_USER_VIEWED_PAID_ADS_FAIL = "GET_USER_VIEWED_PAID_ADS_FAIL";

export const GET_USER_SAVED_FREE_ADS_REQUEST = "GET_USER_SAVED_FREE_ADS_REQUEST";
export const GET_USER_SAVED_FREE_ADS_SUCCESS = "GET_USER_SAVED_FREE_ADS_SUCCESS";
export const GET_USER_SAVED_FREE_ADS_FAIL = "GET_USER_SAVED_FREE_ADS_FAIL";

export const GET_USER_SAVED_PAID_ADS_REQUEST = "GET_USER_SAVED_PAID_ADS_REQUEST";
export const GET_USER_SAVED_PAID_ADS_SUCCESS = "GET_USER_SAVED_PAID_ADS_SUCCESS";
export const GET_USER_SAVED_PAID_ADS_FAIL = "GET_USER_SAVED_PAID_ADS_FAIL";

export const REVIEW_SELLER_FREE_ADS_REQUEST = "REVIEW_SELLER_FREE_ADS_REQUEST";
export const REVIEW_SELLER_FREE_ADS_SUCCESS = "REVIEW_SELLER_FREE_ADS_SUCCESS";
export const REVIEW_SELLER_FREE_ADS_FAIL = "REVIEW_SELLER_FREE_ADS_FAIL";

export const REVIEW_SELLER_PAID_ADS_REQUEST = "REVIEW_SELLER_PAID_ADS_REQUEST";
export const REVIEW_SELLER_PAID_ADS_SUCCESS = "REVIEW_SELLER_PAID_ADS_SUCCESS";
export const REVIEW_SELLER_PAID_ADS_FAIL = "REVIEW_SELLER_PAID_ADS_FAIL";

export const GET_REVIEW_SELLER_FREE_ADS_REQUEST = "REVIEW_SELLER_FREE_ADS_REQUEST";
export const GET_REVIEW_SELLER_FREE_ADS_SUCCESS = "REVIEW_SELLER_FREE_ADS_SUCCESS";
export const GET_REVIEW_SELLER_FREE_ADS_FAIL = "REVIEW_SELLER_FREE_ADS_FAIL";

export const GET_REVIEW_SELLER_PAID_ADS_REQUEST = "REVIEW_SELLER_PAID_ADS_REQUEST";
export const GET_REVIEW_SELLER_PAID_ADS_SUCCESS = "REVIEW_SELLER_PAID_ADS_SUCCESS";
export const GET_REVIEW_SELLER_PAID_ADS_FAIL = "REVIEW_SELLER_PAID_ADS_FAIL";

export const APPLY_PROMO_CODE_REQUEST = "APPLY_PROMO_CODE_REQUEST";
export const APPLY_PROMO_CODE_SUCCESS = "APPLY_PROMO_CODE_SUCCESS";
export const APPLY_PROMO_CODE_FAIL = "APPLY_PROMO_CODE_FAIL";

export const GET_SELLER_PAID_ADS_CHARGES_REQUEST = "GET_SELLER_PAID_ADS_CHARGES_REQUEST";
export const GET_SELLER_PAID_ADS_CHARGES_SUCCESS = "GET_SELLER_PAID_ADS_CHARGES_SUCCESS";
export const GET_SELLER_PAID_ADS_CHARGES_FAIL = "GET_SELLER_PAID_ADS_CHARGES_FAIL";

export const PAY_ADS_CHARGES_REQUEST = "PAY_ADS_CHARGES_REQUEST";
export const PAY_ADS_CHARGES_SUCCESS = "PAY_ADS_CHARGES_SUCCESS";
export const PAY_ADS_CHARGES_FAIL = "PAY_ADS_CHARGES_FAIL";

export const GET_PAID_ADS_CHARGES_RECEIPT_REQUEST = "GET_PAID_ADS_CHARGES_RECEIPT_REQUEST";
export const GET_PAID_ADS_CHARGES_RECEIPT_SUCCESS = "GET_PAID_ADS_CHARGES_RECEIPT_SUCCESS";
export const GET_PAID_ADS_CHARGES_RECEIPT_FAIL = "GET_PAID_ADS_CHARGES_RECEIPT_FAIL";

export const CLEAR_SELLER_FREE_AD_MESSAGE_COUNTER_REQUEST = "CLEAR_SELLER_FREE_AD_MESSAGE_COUNTER_REQUEST";
export const CLEAR_SELLER_FREE_AD_MESSAGE_COUNTER_SUCCESS = "CLEAR_SELLER_FREE_AD_MESSAGE_COUNTER_SUCCESS";
export const CLEAR_SELLER_FREE_AD_MESSAGE_COUNTER_FAIL = "CLEAR_SELLER_FREE_AD_MESSAGE_COUNTER_FAIL";

export const CLEAR_BUYER_FREE_AD_MESSAGE_COUNTER_REQUEST = "CLEAR_BUYER_FREE_AD_MESSAGE_COUNTER_REQUEST";
export const CLEAR_BUYER_FREE_AD_MESSAGE_COUNTER_SUCCESS = "CLEAR_BUYER_FREE_AD_MESSAGE_COUNTER_SUCCESS";
export const CLEAR_BUYER_FREE_AD_MESSAGE_COUNTER_FAIL = "CLEAR_BUYER_FREE_AD_MESSAGE_COUNTER_FAIL";

export const CLEAR_SELLER_PAID_AD_MESSAGE_COUNTER_REQUEST = "CLEAR_SELLER_PAID_AD_MESSAGE_COUNTER_REQUEST";
export const CLEAR_SELLER_PAID_AD_MESSAGE_COUNTER_SUCCESS = "CLEAR_SELLER_PAID_AD_MESSAGE_COUNTER_SUCCESS";
export const CLEAR_SELLER_PAID_AD_MESSAGE_COUNTER_FAIL = "CLEAR_SELLER_PAID_AD_MESSAGE_COUNTER_FAIL";

export const CLEAR_BUYER_PAID_AD_MESSAGE_COUNTER_REQUEST = "CLEAR_BUYER_PAID_AD_MESSAGE_COUNTER_REQUEST";
export const CLEAR_BUYER_PAID_AD_MESSAGE_COUNTER_SUCCESS = "CLEAR_BUYER_PAID_AD_MESSAGE_COUNTER_SUCCESS";
export const CLEAR_BUYER_PAID_AD_MESSAGE_COUNTER_FAIL = "CLEAR_BUYER_PAID_AD_MESSAGE_COUNTER_FAIL";

export const GET_ACTIVE_BUYER_FREE_AD_MESSAGES_REQUEST = "GET_ACTIVE_BUYER_FREE_AD_MESSAGES_REQUEST";
export const GET_ACTIVE_BUYER_FREE_AD_MESSAGES_SUCCESS = "GET_ACTIVE_BUYER_FREE_AD_MESSAGES_SUCCESS";
export const GET_ACTIVE_BUYER_FREE_AD_MESSAGES_FAIL = "GET_ACTIVE_BUYER_FREE_AD_MESSAGES_FAIL";

export const GET_ACTIVE_BUYER_PAID_AD_MESSAGES_REQUEST = "GET_ACTIVE_BUYER_PAID_AD_MESSAGES_REQUEST";
export const GET_ACTIVE_BUYER_PAID_AD_MESSAGES_SUCCESS = "GET_ACTIVE_BUYER_PAID_AD_MESSAGES_SUCCESS";
export const GET_ACTIVE_BUYER_PAID_AD_MESSAGES_FAIL = "GET_ACTIVE_BUYER_PAID_AD_MESSAGES_FAIL";



