// recommenderConstants.js
export const GET_USER_RECOMMENDED_FREE_ADS_REQUEST = 'GET_USER_RECOMMENDED_FREE_ADS_REQUEST';
export const GET_USER_RECOMMENDED_FREE_ADS_SUCCESS = 'GET_USER_RECOMMENDED_FREE_ADS_SUCCESS';
export const GET_USER_RECOMMENDED_FREE_ADS_FAIL = 'GET_USER_RECOMMENDED_FREE_ADS_FAIL';

export const GET_USER_RECOMMENDED_PAID_ADS_REQUEST = 'GET_USER_RECOMMENDED_PAID_ADS_REQUEST';
export const GET_USER_RECOMMENDED_PAID_ADS_SUCCESS = 'GET_USER_RECOMMENDED_PAID_ADS_SUCCESS';
export const GET_USER_RECOMMENDED_PAID_ADS_FAIL = 'GET_USER_RECOMMENDED_PAID_ADS_FAIL';


